import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import BodyStyleManager from '../components/BodyStyleManager';

const cairoRegular = localFont({
  src: '../../public/fonts/Cairo-Regular.woff2',
  variable: '--font-cairo-regular',
});

const cairoBold = localFont({
  src: '../../public/fonts/Cairo-Bold.woff2',
  variable: '--font-cairo-bold',
});

export const metadata: Metadata = {
  title: 'منصة صحة - تسجيل الدخول',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairoRegular.variable} ${cairoBold.variable}`}>
        <BodyStyleManager />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
